version: "2"
run:
  tests: true
linters:
  enable:
    - godot
    - misspell
    - testifylint
  settings:
    misspell:
      locale: US
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/shottaneflow/avito
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
